API example notebook improvements
asreview/asreview pull request #1165
Opened 2022-06-16 08:33 UTC by PeterLombaers

The example simulation now uses a fixed seed. There is an example of getting the settings from the state. There is an example of joining the state to the dataset.

2022-06-16 09:35 UTC, J535D165 requested changes
Thanks!

2022-06-16 09:35 UTC, J535D165 commented on docs/source/example_api_asreview_file.ipynb
> +    "    print(state.settings_metadata)"
Maybe use `pprint`?

2022-06-16 09:35 UTC, J535D165 commented on docs/source/example_api_asreview_file.ipynb
> +   "execution_count": 2,
Please reset the kernel and rerun the notebook. This avoids non-linear execution errors and changes in git.

2022-06-22 14:41 UTC, Rensvandeschoot requested changes

2022-06-22 14:41 UTC, Rensvandeschoot commented on docs/source/example_api_asreview_file.ipynb
> +       "{'version': '1.0+8.gf67a5bb',\n",
Should we change this to v1.1 when we release the next version of ASReview LAB?

2022-06-22 14:41 UTC, Rensvandeschoot commented on docs/source/example_api_asreview_file.ipynb
> +    "You can join the data in the state to the original dataset."
```suggestion
    "You can merge the information from the state file with the original dataset."
```

2022-06-22 14:41 UTC, Rensvandeschoot commented on docs/source/example_api_asreview_file.ipynb
> +    "dataset_with_results = dataset.df.join(df.set_index('record_id'))\n",
```suggestion
    "dataset_with_results = dataset.df.join(df.set_index('record_id'))\n",
    "dataset_with_results.to_csv('data_and_state_merged.csv', index=False)",
```

2022-06-28 08:53 UTC, merged

2022-06-28 08:54 UTC, J535D165 commented
Nice!