Add community button to frond end menu
asreview/asreview pull request #1211
Opened 2022-09-08 14:32 UTC by gimoAI

This PR adds a community button as discussed in https://github.com/asreview/asreview/issues/1209

![community_button](https://user-images.githubusercontent.com/65157657/189149395-3848b375-4e8f-45ec-b161-aa7722f37518.png)

The chosen icon is unavailable in the 5.0.1 version of @miu/icons-material package, hence the update to the newest version.

2022-09-08 18:03 UTC, J535D165 requested changes
Thanks. And welcome to the project!

2022-09-08 18:03 UTC, J535D165 commented on asreview/webapp/src/Components/DrawerItemContainer.js
> +import { Help, Payment, Settings, Diversity3 } from "@mui/icons-material";
Can you order the imports alphabetically?

2022-09-08 18:03 UTC, J535D165 commented on asreview/webapp/src/Components/DrawerItemContainer.js
> +import { donateURL, communityURL, projectModes, projectStatuses } from "../globals.js";
Same

2022-09-09 02:03 UTC, terrymyc reviewed
Thanks! Can you update the corresponding screenshots in the documentation? Please follow the development [guideline](https://github.com/asreview/asreview/blob/master/DEVELOPMENT.md#documentation).

2022-09-10 14:19 UTC, merged

2022-09-10 14:20 UTC, J535D165 commented
Very nice @gimoAI !