update docstring on deduplication
asreview/asreview pull request #1231
Opened 2022-09-27 09:12 UTC by gimoAI

update docstring on deduplication to explicitly state that a PID such as DOI will only be used if available

2022-09-27 10:00 UTC, J535D165 commented on docs/source/project_create.rst
> +    After adding your dataset, ASReview LAB prints the approximate number of duplicates.
```suggestion
    After adding your dataset, ASReview LAB shows the approximate number of duplicates.
```

2022-09-27 12:09 UTC, Rensvandeschoot requested changes

2022-09-27 12:09 UTC, Rensvandeschoot commented on asreview/data/base.py
> +        on a persistent identifier (PID) such as DOI.
```suggestion
        on a persistent identifier (PID) such as the Digital Object Identifier (`DOI <https://www.doi.org/>`_).
```

2022-09-27 12:09 UTC, Rensvandeschoot commented on asreview/data/base.py
> +        on a persistent identifier (PID) such as DOI.
```suggestion
        on a persistent identifier (PID) such the Digital Object Identifier (`DOI <https://www.doi.org/>`_).
```

2022-09-27 12:09 UTC, Rensvandeschoot commented on docs/source/project_create.rst
> +    This number is based on duplicate titles and abstracts and if available, on DOIs.
```suggestion
    This number is based on duplicate titles and abstracts and if available, on the Digital Object Identifier (`DOI <https://www.doi.org/>`_).
```

2022-09-27 13:38 UTC, Rensvandeschoot approved these changes

2022-10-03 09:07 UTC, J535D165 approved these changes

2022-10-03 09:07 UTC, merged