add expert mode to elas game
asreview/asreview pull request #1588
Opened 2023-11-17 18:38 UTC by allardw

2023-11-18 19:30 UTC, J535D165 requested changes
Thanks for your contribution! Please resolve the comment. Will test and merge soon.

2023-11-18 19:30 UTC, J535D165 commented on asreview/webapp/src/Components/ElasGame.js
> +  // }, []);
Please remove or activate these lines.

2023-11-18 19:31 UTC, J535D165 commented
And I like the Elas lollypop :)

2023-11-19 18:07 UTC, Rensvandeschoot commented on asreview/webapp/src/Components/ElasGame.js
> +  // }, []);
solved

2023-11-20 12:04 UTC, J535D165 requested changes
I run into the following:

- Attempt counter doesn't reset when changing modes. 
- Holding the cheat key results in a flickering dialog. It might be better (and easier to implement) to show the cheat when the C key is down and release the cheat mode when the key is up.

2023-11-22 20:02 UTC, Rensvandeschoot commented
Changes:

- improved the logic for the different modes
- added an independent counter for the modes 
- removed scoring from the title and placed the scoring board on top of box
- added reset button
- fixed re-shuffling after switching modes

to do:
- [ ] Holding the cheat key results in a flickering dialog.



![game_expert](https://github.com/asreview/asreview/assets/36502709/7c5e6aeb-b495-4295-ba6b-c290a9cae3b4)

2023-12-12 15:00 UTC, J535D165 commented on asreview/webapp/src/Components/ElasGame.js
> +    imagesArrayExpert: initialShuffle("expert"),
It's nice to see you removed these and integrated them into 1. These should get removed.

2023-12-12 15:02 UTC, J535D165 commented on asreview/webapp/src/Components/ElasGame.js
> +    isExpertCompleted: false,
I prefer not to have different behavior for different games. `isComplete: false`

2023-12-14 21:35 UTC, J535D165 approved these changes

2023-12-14 21:56 UTC, merged