Rename 'debug_label' to 'initial_label' in export file
asreview/asreview pull request #1611
Opened 2023-12-14 07:48 UTC by Rensvandeschoot

2023-12-30 12:03 UTC, J535D165 requested changes
Thanks. 

In general, if possible, let's use `ASReviewData.to_file`. 

A unit test would be so nice to have for this one.

2023-12-30 12:03 UTC, J535D165 commented on asreview/webapp/api/projects.py
> +                    columns={'debug_label': 'label_included'}, inplace=True)
```suggestion
                as_data.df.rename(
                    columns={'debug_label': 'label_included'}, inplace=True)
```

2023-12-30 12:03 UTC, J535D165 commented on asreview/webapp/api/projects.py
> -            labels=labeled.values.tolist(),
Can't we make use of this?

2024-01-04 09:12 UTC, Rensvandeschoot commented
This PR can be closed as it is implemented in [86a9038](https://github.com/asreview/asreview/pull/1623/commits/86a90382feb2b2262f21f0ec619c5e0e3657497f)

2024-01-04 09:12 UTC, closed without merging