add warning to upload clean data without duplicates or missing abstracts
asreview/asreview pull request #428
Opened 2020-12-02 19:33 UTC by Rensvandeschoot

2020-12-03 07:11 UTC, SagevdBrand commented on docs/source/features/pre_screening.rst
> +    If you upload your own data make sure to remove duplicates and make sure
Perhaps this sentence can be shortened to:
"If you upload your own data, make sure to remove duplicates and to retrieve as many abstracts as possible (`don't know how (..))."

2020-12-03 07:13 UTC, SagevdBrand reviewed
Nice! Thanks for highlighting this for the users! I only have a small comment for the first sentence 👍

2020-12-03 15:09 UTC, GerbrichFerdinands requested changes
Nice, great addition to the docs. These changes give two warnings at the moment that need to be fixed.

2020-12-03 15:09 UTC, GerbrichFerdinands commented on docs/source/lab/simulation.rst
> +    has to offer you.
Maybe this is not the right place, as the ideal situation, the cleaning has happened before you run a simulation. Then, a simulation shows your process as is. On the other hand, I see the value of mentioning the GIGO principle here.

2020-12-04 15:29 UTC, merged

2020-12-04 15:30 UTC, J535D165 commented
Thanks @Rensvandeschoot @GerbrichFerdinands and @SagevdBrand!