update covid info
asreview/asreview pull request #768
Opened 2021-10-01 13:08 UTC by JTeijema

Based on PR #765, adds new info on the covid-19 dataset extension

2021-10-01 13:09 UTC, JTeijema commented
I cant edit #765, but I did pull from that branch. Merge 765 first.

2021-10-04 08:54 UTC, J535D165 requested changes

2021-10-04 08:54 UTC, J535D165 commented on docs/source/extensions/extension_covid19.rst
> +#########################
Why do you change the header structure?

2021-10-04 08:59 UTC, Rensvandeschoot approved these changes

2021-10-04 09:00 UTC, J535D165 commented on docs/source/extensions/overview_extensions.rst
> +    - `Github <https://github.com/asreview/asreview-extension-vocab-extractor>`__
```suggestion

```

2021-10-04 09:03 UTC, J535D165 commented on docs/source/extensions/overview_extensions.rst
> +
```suggestion
```

2021-10-04 09:03 UTC, J535D165 commented on docs/source/extensions/extension_covid19.rst
>  -----------------
```suggestion
----------------
```

2021-10-04 09:04 UTC, J535D165 approved these changes

2021-10-04 09:07 UTC, merged