Add ML FE to documentation
asreview/asreview pull request #970
Opened 2022-02-07 11:21 UTC by JTeijema

This PR will add the multilingual feature extractor to the documentation.

2022-02-07 11:22 UTC, JTeijema commented
The updates docs look like this: 
![image](https://user-images.githubusercontent.com/28191416/152778974-304dabc3-addd-4d8f-89dd-9110c4bd5f00.png)

2022-02-08 13:43 UTC, Rensvandeschoot approved these changes

2022-02-14 13:16 UTC, J535D165 requested changes
Thanks

2022-02-14 13:16 UTC, J535D165 commented on docs/source/extensions/overview_extensions.rst
> +      day be integrated to the core.
```suggestion
      This extension adds two feature extractors that extract vocabulary and
      vector matrices during simulation phases for research purposes.
```

2022-02-14 13:16 UTC, J535D165 commented on docs/source/extensions/overview_extensions.rst
> +      day be integrated to the core.
Might be better to file an issue about this and discuss it over there.

2022-02-14 13:16 UTC, J535D165 commented on docs/source/extensions/overview_extensions.rst
> +* Multilingual Feature Extraction
```suggestion
* Feature Extraction Multilingual
```

2022-02-14 13:16 UTC, J535D165 commented on docs/source/extensions/overview_extensions.rst
> +* Multilingual Feature Extraction
Consistent with other one.

2022-03-03 08:52 UTC, Rensvandeschoot approved these changes

2022-03-04 11:51 UTC, J535D165 approved these changes

2022-03-04 11:51 UTC, merged